### ISSUE TITLE
Plugin doesn't work in iOS (cordova 3.5)

### ISSUE THREAD

**Issue by optikalefx** [floatinghotpot/cordova-plugin-nativeaudio#12]
Getting build errors when using this plugin.  

```
sclark:sixtyvocab sean$ cordova --version
3.5.0-0.2.4
sclark:sixtyvocab sean$ phonegap --version
3.5.0-0.20.4
```

error here

```
Undefined symbols for architecture i386:
  "_AudioServicesCreateSystemSoundID", referenced from:
      -[LowLatencyAudio preloadFX:] in LowLatencyAudio.o
  "_AudioServicesDisposeSystemSoundID", referenced from:
      -[LowLatencyAudio unload:] in LowLatencyAudio.o
  "_AudioServicesPlaySystemSound", referenced from:
      -[LowLatencyAudio play:] in LowLatencyAudio.o
   ld: symbol(s) not found for architecture i386
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Xcode throws the same error
http://cl.ly/image/120r0s3r111f

More of the stack here

```
Ld build/emulator/sixtyvocab.app/sixtyvocab normal i386
    cd /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sean/Development/adt-bundle-mac-x86_64-20140321/sdk/platform-tools:/Users/sean/Development/adt-bundle-mac-x86_64-20140321/sdk/tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk -L/Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/emulator -F/Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/emulator -filelist /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/sixtyvocab.build/Debug-iphonesimulator/sixtyvocab.build/Objects-normal/i386/sixtyvocab.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -force_load /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/emulator/libCordova.a -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework AssetsLibrary /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/emulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreLocation -lz -Xlinker -dependency_info -Xlinker /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/sixtyvocab.build/Debug-iphonesimulator/sixtyvocab.build/Objects-normal/i386/sixtyvocab_dependency_info.dat -o /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/build/emulator/sixtyvocab.app/sixtyvocab
Undefined symbols for architecture i386:
  "_AudioServicesCreateSystemSoundID", referenced from:
      -[LowLatencyAudio preloadFX:] in LowLatencyAudio.o
  "_AudioServicesDisposeSystemSoundID", referenced from:
      -[LowLatencyAudio unload:] in LowLatencyAudio.o
  "_AudioServicesPlaySystemSound", referenced from:
      -[LowLatencyAudio play:] in LowLatencyAudio.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

>> ** BUILD FAILED **
>> 
>> 
>> The following build commands failed:
>>  Ld build/emulator/sixtyvocab.app/sixtyvocab normal i386
>> (1 failure)
>> { [Error: /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/cordova/build: Command failed with exit code 65] code: 65 }
   [error] /Applications/MAMP/htdocs/sixtyvocab/phonegap/platforms/ios/cordova/build: Command failed with exit code 65
```

**Comment by sebastianconcept** [comment]
Thanks for the pointer @SidneyS 

In case others, like me today, didn't know how to add those frameworks:
http://stackoverflow.com/questions/3352664/how-to-add-existing-frameworks-in-xcode-4

**Comment by optikalefx** [comment]
@sebastianconcept the newest code installs these for you however. You don't need to install them manually
